# This defines which application properties will be active.
spring:
  profiles:
    active: dev # dev or prod
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url:
#server:
#  port: 80

