spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://easybites-db-instance.cdm8aruzrwwy.us-east-2.rds.amazonaws.com/easybites
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username : /easybites/db/credentials
  jpa:
    hibernate:
      ddl-auto: none # Turn off the DDL auto generation. We prevent spring boot from modifying DB schema